import { Video } from "../types/types";

export const useVideos = (): {
  videos: Video[];
  findVideo: (id: string) => Video | undefined;
} => {
  // Videos thumbnail, title, creator name, basic details
  const videos = [
    {
      id: "vid_001",
      thumbnail: "https://picsum.photos/seed/1/320/180",
      title: "Getting Started with React",
      creator: "Code Academy",
      description:
        "Learn the fundamentals of React and component-based development.",
    },
    {
      id: "vid_002",
      thumbnail: "https://picsum.photos/seed/2/320/180",
      title: "TypeScript for Beginners",
      creator: "Dev Central",
      description: "A practical introduction to TypeScript and static typing.",
    },
    {
      id: "vid_003",
      thumbnail: "https://picsum.photos/seed/3/320/180",
      title: "Next.js Crash Course",
      creator: "Frontend Masters",
      description: "Build modern web applications using Next.js.",
    },
    {
      id: "vid_004",
      thumbnail: "https://picsum.photos/seed/4/320/180",
      title: "Understanding CSS Grid",
      creator: "Design Lab",
      description: "Master CSS Grid layout with real-world examples.",
    },
    {
      id: "vid_005",
      thumbnail: "https://picsum.photos/seed/5/320/180",
      title: "Tailwind CSS Essentials",
      creator: "UI Builder",
      description: "Learn utility-first styling with Tailwind CSS.",
    },
    {
      id: "vid_006",
      thumbnail: "https://picsum.photos/seed/6/320/180",
      title: "Node.js Fundamentals",
      creator: "Backend Pro",
      description: "Understand how Node.js works and build APIs.",
    },
    {
      id: "vid_007",
      thumbnail: "https://picsum.photos/seed/7/320/180",
      title: "Express.js API Tutorial",
      creator: "Code Academy",
      description: "Build RESTful APIs with Express.js.",
    },
    {
      id: "vid_008",
      thumbnail: "https://picsum.photos/seed/8/320/180",
      title: "Prisma ORM Deep Dive",
      creator: "Database Hub",
      description: "Learn database access using Prisma ORM.",
    },
    {
      id: "vid_009",
      thumbnail: "https://picsum.photos/seed/9/320/180",
      title: "PostgreSQL Basics",
      creator: "SQL Experts",
      description: "Get started with PostgreSQL database management.",
    },
    {
      id: "vid_010",
      thumbnail: "https://picsum.photos/seed/10/320/180",
      title: "Authentication with NextAuth",
      creator: "Auth Masters",
      description: "Secure your applications with authentication.",
    },
    {
      id: "vid_011",
      thumbnail: "https://picsum.photos/seed/11/320/180",
      title: "Building an E-Commerce App",
      creator: "Full Stack Dev",
      description: "Create a complete e-commerce application from scratch.",
    },
    {
      id: "vid_012",
      thumbnail: "https://picsum.photos/seed/12/320/180",
      title: "JavaScript ES2025 Features",
      creator: "JS Weekly",
      description: "Explore the latest features in JavaScript.",
    },
    {
      id: "vid_013",
      thumbnail: "https://picsum.photos/seed/13/320/180",
      title: "Responsive Design Principles",
      creator: "Design Lab",
      description: "Build responsive layouts for all devices.",
    },
    {
      id: "vid_014",
      thumbnail: "https://picsum.photos/seed/14/320/180",
      title: "State Management with Zustand",
      creator: "Frontend Masters",
      description: "Manage application state using Zustand.",
    },
    {
      id: "vid_015",
      thumbnail: "https://picsum.photos/seed/15/320/180",
      title: "Redux Toolkit Explained",
      creator: "Dev Central",
      description: "Simplify Redux using Redux Toolkit.",
    },
    {
      id: "vid_016",
      thumbnail: "https://picsum.photos/seed/16/320/180",
      title: "Building Reusable Components",
      creator: "UI Builder",
      description: "Create scalable and reusable UI components.",
    },
    {
      id: "vid_017",
      thumbnail: "https://picsum.photos/seed/17/320/180",
      title: "Advanced React Hooks",
      creator: "Code Academy",
      description: "Master custom hooks and advanced React patterns.",
    },
    {
      id: "vid_018",
      thumbnail: "https://picsum.photos/seed/18/320/180",
      title: "Deploying with Vercel",
      creator: "Cloud Experts",
      description: "Deploy your Next.js applications effortlessly.",
    },
    {
      id: "vid_019",
      thumbnail: "https://picsum.photos/seed/19/320/180",
      title: "Docker for Developers",
      creator: "Backend Pro",
      description: "Containerize applications with Docker.",
    },
    {
      id: "vid_020",
      thumbnail: "https://picsum.photos/seed/20/320/180",
      title: "Git & GitHub Workflow",
      creator: "Dev Central",
      description: "Collaborate effectively using Git and GitHub.",
    },
    {
      id: "vid_021",
      thumbnail: "https://picsum.photos/seed/21/320/180",
      title: "REST API Best Practices",
      creator: "API Masters",
      description: "Design maintainable and scalable APIs.",
    },
    {
      id: "vid_022",
      thumbnail: "https://picsum.photos/seed/22/320/180",
      title: "GraphQL Introduction",
      creator: "Full Stack Dev",
      description: "Learn the basics of GraphQL APIs.",
    },
    {
      id: "vid_023",
      thumbnail: "https://picsum.photos/seed/23/320/180",
      title: "Modern UI Design Trends",
      creator: "Design Lab",
      description: "Explore current trends in web design.",
    },
    {
      id: "vid_024",
      thumbnail: "https://picsum.photos/seed/24/320/180",
      title: "Accessibility in Web Apps",
      creator: "Frontend Masters",
      description: "Make your applications accessible to everyone.",
    },
    {
      id: "vid_025",
      thumbnail: "https://picsum.photos/seed/25/320/180",
      title: "Testing React Applications",
      creator: "QA Hub",
      description: "Write reliable tests for React apps.",
    },
    {
      id: "vid_026",
      thumbnail: "https://picsum.photos/seed/26/320/180",
      title: "Unit Testing with Jest",
      creator: "QA Hub",
      description: "Learn unit testing using Jest.",
    },
    {
      id: "vid_027",
      thumbnail: "https://picsum.photos/seed/27/320/180",
      title: "CI/CD Pipeline Setup",
      creator: "Cloud Experts",
      description: "Automate deployments with CI/CD pipelines.",
    },
    {
      id: "vid_028",
      thumbnail: "https://picsum.photos/seed/28/320/180",
      title: "Web Security Essentials",
      creator: "Security First",
      description: "Protect your applications from common threats.",
    },
    {
      id: "vid_029",
      thumbnail: "https://picsum.photos/seed/29/320/180",
      title: "OAuth Authentication Guide",
      creator: "Auth Masters",
      description: "Implement OAuth authentication flows.",
    },
    {
      id: "vid_030",
      thumbnail: "https://picsum.photos/seed/30/320/180",
      title: "Performance Optimization",
      creator: "Frontend Masters",
      description: "Improve loading speed and performance.",
    },
    {
      id: "vid_031",
      thumbnail: "https://picsum.photos/seed/31/320/180",
      title: "SEO for Next.js",
      creator: "Marketing Tech",
      description: "Optimize your Next.js apps for search engines.",
    },
    {
      id: "vid_032",
      thumbnail: "https://picsum.photos/seed/32/320/180",
      title: "Building Dashboards",
      creator: "UI Builder",
      description: "Create professional admin dashboards.",
    },
    {
      id: "vid_033",
      thumbnail: "https://picsum.photos/seed/33/320/180",
      title: "Data Fetching Strategies",
      creator: "Code Academy",
      description: "Compare SSR, SSG, and client-side fetching.",
    },
    {
      id: "vid_034",
      thumbnail: "https://picsum.photos/seed/34/320/180",
      title: "WebSockets Explained",
      creator: "Backend Pro",
      description: "Enable real-time communication in applications.",
    },
    {
      id: "vid_035",
      thumbnail: "https://picsum.photos/seed/35/320/180",
      title: "MongoDB Basics",
      creator: "Database Hub",
      description: "Introduction to MongoDB and NoSQL databases.",
    },
    {
      id: "vid_036",
      thumbnail: "https://picsum.photos/seed/36/320/180",
      title: "Advanced SQL Queries",
      creator: "SQL Experts",
      description: "Improve database performance with SQL.",
    },
    {
      id: "vid_037",
      thumbnail: "https://picsum.photos/seed/37/320/180",
      title: "Microservices Architecture",
      creator: "System Design",
      description: "Understand microservices and distributed systems.",
    },
    {
      id: "vid_038",
      thumbnail: "https://picsum.photos/seed/38/320/180",
      title: "System Design Interview Prep",
      creator: "Tech Career",
      description: "Prepare for system design interviews.",
    },
    {
      id: "vid_039",
      thumbnail: "https://picsum.photos/seed/39/320/180",
      title: "Building SaaS Products",
      creator: "Startup Hub",
      description: "Learn how to build and launch SaaS applications.",
    },
    {
      id: "vid_040",
      thumbnail: "https://picsum.photos/seed/40/320/180",
      title: "AI Integration for Web Apps",
      creator: "AI Builders",
      description: "Integrate AI capabilities into your projects.",
    },
    {
      id: "vid_041",
      thumbnail: "https://picsum.photos/seed/41/320/180",
      title: "Prompt Engineering Basics",
      creator: "AI Builders",
      description: "Write effective prompts for AI models.",
    },
    {
      id: "vid_042",
      thumbnail: "https://picsum.photos/seed/42/320/180",
      title: "LangChain Introduction",
      creator: "AI Builders",
      description: "Build AI-powered workflows with LangChain.",
    },
    {
      id: "vid_043",
      thumbnail: "https://picsum.photos/seed/43/320/180",
      title: "Building Chatbots",
      creator: "AI Builders",
      description: "Create conversational AI applications.",
    },
    {
      id: "vid_044",
      thumbnail: "https://picsum.photos/seed/44/320/180",
      title: "Machine Learning Overview",
      creator: "Data Science Hub",
      description: "Understand the basics of machine learning.",
    },
    {
      id: "vid_045",
      thumbnail: "https://picsum.photos/seed/45/320/180",
      title: "Python for Developers",
      creator: "Code Academy",
      description: "Learn Python programming for web development.",
    },
    {
      id: "vid_046",
      thumbnail: "https://picsum.photos/seed/46/320/180",
      title: "Building APIs with FastAPI",
      creator: "Backend Pro",
      description: "Develop fast APIs using FastAPI.",
    },
    {
      id: "vid_047",
      thumbnail: "https://picsum.photos/seed/47/320/180",
      title: "Cloud Computing Basics",
      creator: "Cloud Experts",
      description: "Introduction to cloud platforms and services.",
    },
    {
      id: "vid_048",
      thumbnail: "https://picsum.photos/seed/48/320/180",
      title: "AWS for Beginners",
      creator: "Cloud Experts",
      description: "Get started with Amazon Web Services.",
    },
    {
      id: "vid_049",
      thumbnail: "https://picsum.photos/seed/49/320/180",
      title: "Kubernetes Fundamentals",
      creator: "DevOps Hub",
      description: "Learn container orchestration with Kubernetes.",
    },
    {
      id: "vid_050",
      thumbnail: "https://picsum.photos/seed/50/320/180",
      title: "Career Roadmap for Full-Stack Developers",
      creator: "Tech Career",
      description: "A guide to becoming a full-stack developer.",
    },
  ];

  // find specific video via id
  const findVideo = (id: string): Video | undefined => {
    return videos.find((v) => v.id === id);
  };
  return { videos, findVideo };
};
